### PR TITLE
Update UserTSconfig.rst

### PR DESCRIPTION
**Pull request by JemalKhachidze**

### CODE REVIEW

**Review by froemken — APPROVED** [review]

**Comment by garvinhicking** [comment]
@JemalKhachidze Many thanks for the contribution, since this possibly also applies to our `main` branch, would you be able to move your patch against the `main` branch instead? This would be something we would want to merge to `main` and from there only to `12.4`. :-)

**Review by brotkrueml — COMMENTED** [review]
Reading through the changes I don't get what the purpose of this patch is?

**Comment by garvinhicking** [comment]
@brotkrueml I'm afraid the rebasing seems to have messed things up a bit.

The change was about some spelling mistakes I believe?! @JemalKhachidze can you maybe start over with a freshly forked or updated "main" and your change applied or see if you can bring this PR in synch?

**Comment by JemalKhachidze** [comment]
I guess I messed PR. I will try to submit new PR on main branch. It is spelling mistake only.

**Pull request closed without merging**
