### PR TITLE
PageTSconfig.rst: Syntax errors, missing imports

### PR DESCRIPTION
**Pull request by fishbone1**
See #244

### CODE REVIEW

**Comment by mbrodala** [comment]
This was fixed with #245 already.

**Comment by mbrodala** [comment]
Can you rebase to reduce this to the `use` imports?

**Review by mbrodala — APPROVED** [review]
Actually it's fine like this. I swear I already had my coffee. :coffee:

**Comment by fishbone1** [comment]
Yes you're right the quotes have already been fixed but then I realized that the extension directory differs from the path given above the code block.

**Pull request merged**
