### PR TITLE
Remove condensedMode from docs

### PR DESCRIPTION
**Pull request by tmotyl**
The setting was removed years ago. See https://forge.typo3.org/issues/56479 and https://forge.typo3.org/issues/24585

### CODE REVIEW

**Comment by marble** [comment]
Do you know about version 7-6, 6-2?

**Comment by tmotyl** [comment]
it was removed in 2011, so 7.6 for sure

**Comment by Chrissitopher** [comment]
According to forge and the commits, it got removed in 6.2. So this change needs a backport to 7-6 and 6-2.

**Comment by marble** [comment]
Applied to: latest, 7-6, 6-2

**Pull request merged**
