### PR TITLE
Typos and language fixes

### PR DESCRIPTION
**Pull request by anubhasy**
I have fixed a few typographical errors and have rewritten a few sentences for clearer meaning.

### CODE REVIEW

**Review by susannemoog — APPROVED** [review]

**Comment by susannemoog** [comment]
Thanks a lot for your contribution :)

**Comment by anubhasy** [comment]
Hi @susannemoog,

How else can I contribute? I can see a lot of language issues but I am unsure of the context. Can you please guide me for the same?

**Comment by susannemoog** [comment]
Hey, what do you mean by context? Are you already in the TYPO3 Slack? If so, you could ping me and we can chat about the topics together and see how I can help you to get started.

**Comment by anubhasy** [comment]
Nope @susannemoog. I am not in the Slack workspace yet. I'm just registering for it. 

I appreciate your offer of help. I'll definitely ping you on the Slack channel to discuss further.

Thanks.

**Pull request merged**
